### ISSUE TITLE
Dropdown Component

### ISSUE THREAD

**Issue by vasyl-shumskyi** [MauriceConrad/Photon#3]
Thanks for the nice components!

It would be so cool if you can add dropdown photon is lacking of:
https://github.com/connors/photon/issues/106

**Comment by ElyaConrad** [comment]
Thank you for the idea! I will do my best to implement it!

**Comment by smeads** [comment]
Curious if there is any update on a dropdown component. If not, can you point me in the right direction on how to best implement one, i.e. bootstrap, vanilla js, etc.?

**Comment by ElyaConrad** [comment]
@smeads Sorry. I did it already and the code is still on my disk. It's not so complicated but I will upload it in the next hours! Sorry, sometimes I'm a mittelbar busy..

**Comment by vasyl-shumskyi** [comment]
Quick question - will dropdown affect header height? :)

<img width="384" alt="screen shot 2017-05-09 at 11 28 11" src="https://cloud.githubusercontent.com/assets/2331802/25841915/b0f11d78-34aa-11e7-814c-f6db0cc0d159.png">

**Comment by ElyaConrad** [comment]
No, just test the sample app within the repo. It's a native macOS menu and therefore it's not related to the DOM. And I don't think that it should do so because normally on macOS Cocoa it also has no effects for the header height.
Or what exactly do you mean?

**Comment by smeads** [comment]
@MauriceConrad that would be great and much appreciated. Also, thanks for Photon, it's a great tool and certainly enjoy using it.

**Comment by ElyaConrad** [comment]
@smeads
 Thank you but always remember that Photon itself is not my project. The original photon project is made by Connor sears. Sadly he stopped development since more than a year. This repo is called "PhotonKit Components" because it contains new component and JavaScript controllers that are just "plugins" because photon is deprecated.
I absolutely want to publish everything as her own frame work because  I absolutely want to publish everything as a own framework because there's no chance  that the original developer continues. 
 But that's something that needs more work. At the moment the components are always standalone because they are just "standalone" fesutures tgat work with photon.
To publish everything as a new framework the structure has to be rethought. I also need windows developers for a metro theme. And everything thing has to be documented one time with a good structure. At the moments it's just a suboptimal solution because connors does not answer and therefore, the original project is deprecated.
