### ISSUE TITLE
Vue warning - <action-inner>

### ISSUE THREAD

**Issue by mikerogne** [MauriceConrad/Photon#31]
> [Vue warn]: Unknown custom element: <action-inner> - did you register the component correctly? For recursive components, make sure to provide the "name" option.

Getting this warning in console when testing the demo app. Screenshot: https://d.pr/i/UlQHl5

**Comment by ElyaConrad** [comment]
This is because Vue.js uses its own custom-element spec which works also in ES5.
This needs to register each custom element as a component. Just ignore this warning.

But because my framework is not dependent from Vue.js and because of the use of Electron (Mostly a new chromium) I am using the new [Custom Elements](https://developer.mozilla.org/en-US/docs/Web/Web_Components/Using_custom_elements) API
