### ISSUE TITLE
Tiny bug: Font-size is not the same for btn-segment (12px) and btn-system (13px)

### ISSUE THREAD

**Issue by vasyl-shumskyi** [MauriceConrad/Photon#7]
I just noticed that font-size is not the same for `btn-segment` and `btn-system`. For `btn-segment` font-size  equals to 12px (set in `photon.css`), meanwhile for `btn-system` it gets overwritten by 13px which is set in `btn.css`

I didn't get too deep and checked additional font parameters like `font-weight`, `letter-spacing`, `padding` etc. 

Maybe it will be wise to use the same stylesheet for `btn-system` and `btn-segment` as a workaround.

**Comment by ElyaConrad** [comment]
# Photon 1.0 RELEASE

## Dear Photon User!

I am very proud to announce the release of Photon version 1.0! You are a follower of Photon and maybe you already know my extension framework „PhotonKit Components“ that extends the original Photon project on a high level. Sadly the original developer @connors was not abled to accept my contributions or answer me at least one time because he seems to be inactive since more than 2 years. This is very sad because Photon is a great tool to design native looking UI’s and there was a lot to do.
I was the only active developer who still keeps the project up to date.

![ShowReel](https://dev.maurice-conrad.eu/img/photon/demo.png)

Somedays I thought about the future of the project and the last commitment of @connors was 2 years ago. I realised that the only solution for the future of the project would be a complete new version 1.0

This release is a hard fork of the original project that redefines everything hardly and replaces the PhotonKitComponents project I made.

## Getting Started

```bash
npm install electron-photon
```

Just have a look at the „ShowReel“ application or ask me for questions ;-)

[GitHub](https://github.com/MauriceConrad/Photon)

[NPM](https://www.npmjs.com/package/electron-photon)


### Questions? Ideas?

[conr.maur@googlemail.com](mailto:conr.maur@googlemail.com)

**Kind regards,**
<br>**Maurice Conrad**
