### ISSUE TITLE
slider range.js attaches sliderVisualCalc to all input events

### ISSUE THREAD

**Issue by morriswinkler-simple** [MauriceConrad/Photon#8]
This code attaches to all input events if I use other input elements this results in errors

```
window.addEventListener("input", function() {
  event.target.sliderVisualCalc();
}, false);
```

No idea how that could be fixed. Open for suggestions.

Cheers

**Comment by morriswinkler-simple** [comment]
i think i fixed it by doing 

```
window.addEventListener("load", function () {
    var sliders = document.getElementsByClassName("slider");
    for (var i = 0; i < sliders.length; i++) {
        sliders[i].sliderVisualCalc();
        sliders[i].addEventListener("input", function () {
            event.target.sliderVisualCalc();
        }, false);
    }
}, false);
// window.addEventListener("input", function() {
//   event.target.sliderVisualCalc();
// }, false);
//console.log(HTMLInputElement.prototype);
```

**Comment by ElyaConrad** [comment]
# Photon 1.0 RELEASE

## Dear Photon User!

I am very proud to announce the release of Photon version 1.0! You are a follower of Photon and maybe you already know my extension framework „PhotonKit Components“ that extends the original Photon project on a high level. Sadly the original developer @connors was not abled to accept my contributions or answer me at least one time because he seems to be inactive since more than 2 years. This is very sad because Photon is a great tool to design native looking UI’s and there was a lot to do.
I was the only active developer who still keeps the project up to date.

![ShowReel](https://dev.maurice-conrad.eu/img/photon/demo.png)

Somedays I thought about the future of the project and the last commitment of @connors was 2 years ago. I realised that the only solution for the future of the project would be a complete new version 1.0

This release is a hard fork of the original project that redefines everything hardly and replaces the PhotonKitComponents project I made.

## Getting Started

```bash
npm install electron-photon
```

Just have a look at the „ShowReel“ application or ask me for questions ;-)

[GitHub](https://github.com/MauriceConrad/Photon)

[NPM](https://www.npmjs.com/package/electron-photon)


### Questions? Ideas?

[conr.maur@googlemail.com](mailto:conr.maur@googlemail.com)

**Kind regards,**
<br>**Maurice Conrad**
